export const ADD_INGREDIENTS = "ADD_INGREDIENTS"
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS"
export const SET_INGREDIENTS = "SET_INGREDIENTS"
export const FETCH_INGREDIENTS_ERROR = "FETCH_INGREDIENTS_ERROR"

export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS"
 export const PURCHASE_BURGER_FAIL ="PURCHASE_BURGER_FAIL"
 export const PURCHASE_BURGER_START ="PURCHASE_BURGER_START" //! sets loading to true