export const SET_INGREDIENTS = "SET_INGREDIENTS"
export const SET_UPDATED_INGREDIENTS = "SET_UPDATED_INGREDIENTS"
export const SET_NEWPRICE = "SET_NEWPRICE"
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS"
